### ISSUE TITLE
file sources do not show up in UI when piping

### ISSUE THREAD

**Issue by ahmadnassri** [codeclimate/javascript-test-reporter#58]
when piping the `lcov` report in:

```shell
$ tap test --coverage --coverage-report=text-lcov | codeclimate-test-reporter
```

branch info and source files do not get parsed and displayed in the UI, though there are no errors or any indicator of this in the CLI.

**Comment by pbrisbin** [comment]
Hi @ahmadnassri sorry for the trouble here.

By "the UI" do you mean the "Test Coverage" tab on codeclimate.com?

Unfortunately, since we process (and validate) the coverage reports as a background job, the CLI reporter can get a 200 success response even though the payload might be found to be invalid later when we process it. I'd be happy to try and find the payload and see if/why it was considered invalid, but I would need to know the repository (name or id) on codeclimate.com that you're submitting coverage for. If you'd prefer to not give that information in this public OSS Issue, please reach out to us at https://codeclimate.com/help.

**Comment by ahmadnassri** [comment]
> By "the UI" do you mean the "Test Coverage" tab on codeclimate.com?

yes

**Comment by ahmadnassri** [comment]
here's an OSS one with recent commits that shows this: 

https://codeclimate.com/github/ahmadnassri/autoenv/coverage

source at: https://github.com/ahmadnassri/autoenv

**Comment by pbrisbin** [comment]
Thank you.

I can see we have 3 payloads accepted, all contain 1 file at 100% coverage, which matches what's displayed in the UI and is what I'd expect given the source of that repository.

```
Time                            Branch  #Files  %       Lines   CI              Sha
April 12, 2017 09:03 EDT	master	1	100.0	11	travis-ci	08e6f42c
April 12, 2017 08:53 EDT	master	1	100.0	10	travis-ci	11e49413
February 21, 2017 12:35 EST	master	1	100.0	3	travis-ci	2c5029fb
```

Can you explain a bit more about what you think is incorrect here?

**Comment by ahmadnassri** [comment]
![image](https://cloud.githubusercontent.com/assets/183195/24967655/d5bec584-1f78-11e7-8768-45e245754290.png)

`index.js` not clickable ... 

here's another OSS one with a mixed result: https://codeclimate.com/github/ahmadnassri/winston-tcp/coverage

**Comment by pbrisbin** [comment]
Ah yes. I can explain that, but it's slightly complicated.

For those links to work, we need to also have an *Analysis* build for the repository at that commit sha. At the time you reported this Issue, our latest analysis for `ahmadnassri/autoenv` was for `2c5029fb`, so the coverage information being shown for `08e6f42c` can't link to a source view.

It looks like this problem has resolved now though; there is a Build for `08e6f42c`. And so, as I'd expect, the links are now working in https://codeclimate.com/github/ahmadnassri/autoenv/coverage.

(It's slightly more complicated in the mixed example, since we might have an analysis for an older commit sha, but we can still display the source code if the specific file's blob-id hasn't changed between the newer coverage information and the older analysis build -- so some of those links do work.)

We're actively working on making this whole situation a bit more sensical and functional in a case like this, but that's how it works today.

The fix in general is to ensure up to date analysis builds are also occurring for the repository where you're reporting coverage. It seems like you've solved that at this point?

**Comment by ahmadnassri** [comment]
@pbrisbin thanks for the detailed response, so to summarize, you're saying the internal codelimiate analysis build was just running behind, so when the coverage was submitted, it disabled the source view until that build analysis came through?

I didn't do anything to solve it ... or in other words, I didn't change anything during the course of this discussion ...

**Comment by pbrisbin** [comment]
According to our logs, around 2 hours ago, someone clicked the *refresh* button for this repository on Code Climate, which triggered an Analysis build of master (at `08e6f42c`). That's what got things working again.

As far as I can tell, Analysis builds for this repository are not being triggered on our end by pushes to master. Which is how all this is meant to stay in sync. This could be because our webhook was removed (or was never present) in GitHub. Without fixing this, coverage payloads which change file contents won't be able to link to source views until and unless the repository is refreshed.

If you'd like some additional help with this, I'd suggest reaching out at https://codeclimate.com/help. Since there seems to be no issue in the reporter, I'd like to close this Issue.

**Comment by ahmadnassri** [comment]
closing this issue for now, I'll test further on our end.
